# Generated by Django 4.0.4 on 2022-05-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_socialsidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialsidebar',
            name='social_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
