# Generated by Django 4.0.4 on 2022-05-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_socialsidebar_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialsidebar',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='socialsidebar',
            name='link_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
