# Generated by Django 4.0.4 on 2022-05-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_socialsidebar_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialsidebar',
            name='background',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
