# Generated by Django 4.0.4 on 2022-05-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_office', models.CharField(blank=True, max_length=255, null=True)),
                ('email_us', models.EmailField(max_length=255, unique=True)),
                ('call_us', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.AlterField(
            model_name='socialsidebar',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
    ]
