# Generated by Django 4.0.4 on 2022-05-23 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_alter_news_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='contacts_us',
            options={'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='socialsidebar',
            options={'verbose_name_plural': 'Социальные сети'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Теги'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news'),
        ),
    ]
